version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"
    open-pull-requests-limit: 6
    labels:
      - "dependencies"
